spring.application.name=PrjSpringAi

#spring.main.web-application-type=none
server.port=${port:8000}

# need to run ollama model: > ollama run qwen2.5
# spring.ai.ollama.base-url=http://localhost:11434
# spring.ai.ollama.chat.options.model=qwen2.5
# spring.ai.ollama.chat.options.model=llava:7b
# spring.ai.ollama.chat.options.temperature=1

# config for model running in a server device
spring.ai.ollama.base-url=http://localhost:11434

# Text models
#spring.ai.ollama.chat.options.model=qwen2.5
#spring.ai.ollama.chat.options.model=qwen2.5:3b
#spring.ai.ollama.chat.options.model=ministral-3:8b
#spring.ai.ollama.chat.options.model=gemma3:4b
#spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.ollama.chat.options.model=qwen3.5:9b
#spring.ai.ollama.chat.options.model=mistral

# Image models
#spring.ai.ollama.chat.options.model=llava:7b
spring.ai.ollama.chat.options.model=qwen2.5vl:7b
#spring.ai.ollama.chat.options.model=qwen3-vl:8b

# models on cloud
# spring.ai.ollama.chat.options.stream=false
# spring.ai.openai.api-key=<your_OpenAi_ApiKey>

# Vector Store properties (for PGVector -> postgresql database)
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=true

#spring.ai.ollama.embedding.model=nomic-embed-text
#spring.ai.ollama.embedding.model=mxbai-embed-large <-- default

# LOG setup
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client=DEBUG

# Database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/db_springai
spring.datasource.username=<db_user>
spring.datasource.password=<db_password>

# Spring Boot can infer this from the URL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# spring-boot application properties key/value
stock.api.key=<your_twelvedata_ApiKey>
stock.api.url=https://api.twelvedata.com/time_series?symbol={0}&interval={1}&outputsize={2}&apikey={3}

